[avr]
exten => s,1,Answer()

 ; --- AJOUT POUR LIMITE DE TEMPS ---
 ; On définit une limite absolue de 900 secondes (15 minutes).
 ; Une fois ce temps écoulé, Asterisk coupera la communication brutalement.
 same => n,Set(TIMEOUT(absolute)=900)
 ; ----------------------------------


 same => n,Ringing()
 same => n,Wait(1)
 
 ; 1. On génère l'UUID
 same => n,Set(UUID=${SHELL(uuidgen | tr -d '\n')})

  ; Sécurité numéro vide (optionnel mais conseillé)
 
 ; --- AJOUT POUR L'ENREGISTREMENT ---
 ; On lance l'enregistrement en arrière-plan. 
 ; Le fichier sera nommé avec l'UUID (ex: 550e8400-e29b-....wav)
 ; --- 1. DEFINITION DE LA DATE ---
 ; %Y=Année, %m=Mois, %d=Jour, %H=Heure, %M=Minute, %S=Seconde
 ;same => n,Set(DATETIME=${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)})
 same => n,Set(DATETIME=${STRFTIME(${EPOCH},Pacific/Noumea,%Y%m%d-%H%M%S)})
 same => n,ExecIf($["${CALLERID(num)}" = ""]?Set(CALLERID(num)=inconnu))
  same => n,MixMonitor(${DATETIME}|${CALLERID(num)}|${UUID}.wav)
 ; -----------------------------------
 
 ; 2. On envoie l'événement AMI pour que Node.js le détecte
 same => n,UserEvent(AVRStart,UUID: ${UUID})

 ; 3. On lance l'audio vers le service IA
 same => n,Dial(AudioSocket/${ARG1}/${UUID})
 
 ; Fin normale
 same => n,Hangup()

; --- EXTENSION DE TIMEOUT (Optionnel) ---
; Quand le temps est écoulé, Asterisk cherche parfois l'extension 'T'.
; Cela permet de voir dans les logs que c'était un timeout et pas une erreur.
exten => T,1,NoOp(=== TIMEOUT 10 MIN ATTEINT ===)
 same => n,Hangup()


; --- EXTENSION DE SECOURS ---
exten => kill,1,NoOp(=== FORCED HANGUP VIA API ===)
 same => n,Hangup()

[demo]
exten => 5001,1,GoSub(avr,s,1(avr-core:5001))