[avr]
exten => s,1,Answer()
 same => n,Ringing()
 same => n,Wait(1)
 
 ; 1. On génère l'UUID
 same => n,Set(UUID=${SHELL(uuidgen | tr -d '\n')})
 
 ; 2. On envoie l'événement AMI pour que Node.js le détecte
 same => n,UserEvent(AVRStart,UUID: ${UUID})

 ; 3. On lance l'audio (options vides entre les virgules si besoin)
 same => n,Dial(AudioSocket/${ARG1}/${UUID})
 
 ; Fin normale (si l'IA raccroche d'elle-même, mais souvent bloqué par le Dial)
 same => n,Hangup()

; --- EXTENSION DE SECOURS (KILL SWITCH) ---
; C'est ici que l'API va rediriger l'appel pour le tuer
exten => kill,1,NoOp(=== FORCED HANGUP VIA API ===)
 same => n,Hangup()

[demo]
exten => 5001,1,GoSub(avr,s,1(avr-core:5001))